version: '3'
services:
    #Gitea
    gitea:
        image: gitea/gitea
        container_name: gitea
        hostname: gitea
        volumes:
            - gitea-data:/data
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "3000:3000"
            - "23:22"
        networks:
            - biowaynet
        restart: always
    ###

    #Eureka Server
    eurekaserver:
        build: ./eurekaserver
        container_name: eurekaserver
        hostname: eurekaserver
        volumes:
            - eurekaserver-data:/usr/app
        ports:
            - 8761:8761
        networks:
            - biowaynet
        restart: always
    ###

    #Microservices
    apigateway:
        build: ./tomcat
        container_name: apigateway
        hostname: apigateway
        volumes:
            - apigateway-data:/usr/local/tomcat/webapps
        ports:
            - 8080:8080
        environment: 
            - TOMCAT_PASSWORD=tomcat
        networks:
            - biowaynet
        depends_on:
            - eurekaserver

    cart:
        build: ./tomcat
        container_name: cart
        hostname: cart
        volumes:
            - cart-data:/usr/local/tomcat/webapps
        ports:
            - 8081:8080
        environment: 
            - TOMCAT_PASSWORD=tomcat
        networks:
            - biowaynet
        depends_on:
            - mongo-seed
            - eurekaserver

    customers:
        build: ./tomcat
        image: tomcat
        container_name: customers
        hostname: customers
        volumes:
            - customers-data:/usr/local/tomcat/webapps
        ports:
            - 8082:8080
        environment: 
            - TOMCAT_PASSWORD=tomcat
        networks:
            - biowaynet
        depends_on:
            - mongo-seed
            - eurekaserver

    identity:
        build: ./tomcat
        image: tomcat
        container_name: identity
        hostname: identity
        volumes:
            - identity-data:/usr/local/tomcat/webapps
        ports:
            - 8084:8080
        environment: 
            - TOMCAT_PASSWORD=tomcat
        networks:
            - biowaynet
        depends_on:
            - mongo-seed
            - eurekaserver

    payments:
        build: ./tomcat
        image: tomcat
        container_name: payments
        hostname: payments
        volumes:
            - payments-data:/usr/local/tomcat/webapps
        ports:
            - 8085:8080
        environment: 
            - TOMCAT_PASSWORD=tomcat
        networks:
            - biowaynet
        depends_on:
            - mongo-seed
            - eurekaserver

    products:
        build: ./tomcat
        image: tomcat
        container_name: products
        hostname: products
        volumes:
            - products-data:/usr/local/tomcat/webapps
        ports:
            - 8086:8080
        environment: 
            - TOMCAT_PASSWORD=tomcat
        networks:
            - biowaynet
        depends_on:
            - mongo-seed
            - eurekaserver
            - ProductSearch

    ProductSearch:
        build: ./tomcat
        image: tomcat
        container_name: ProductSearch
        hostname: ProductSearch
        volumes:
            - ProductSearch-data:/usr/local/tomcat/webapps
        ports:
            - 8087:8080
        environment: 
            - TOMCAT_PASSWORD=tomcat
        networks:
            - biowaynet
        depends_on:
            - mongo-seed
            - eurekaserver

    purchases:
        build: ./tomcat
        image: tomcat
        container_name: purchases
        hostname: purchases
        volumes:
            - purchases-data:/usr/local/tomcat/webapps
        ports:
            - 8088:8080
        environment: 
            - TOMCAT_PASSWORD=tomcat
        networks:
            - biowaynet
        depends_on:
            - mongo-seed
            - eurekaserver

    suppliers:
        build: ./tomcat
        image: tomcat
        container_name: suppliers
        container_name: suppliers
        volumes:
            - suppliers-data:/usr/local/tomcat/webapps
        ports:
            - 8089:8080
        environment: 
            - TOMCAT_PASSWORD=tomcat
        networks:
            - biowaynet
        depends_on:
            - mongo-seed
            - eurekaserver
    ###

    #Databases
    mongo:
        image: mongo
        container_name: mongo
        hostname: mongo
        networks:
            - biowaynet 
        ports:
            - "27027:27017"
        restart: always

    #Test data import
    mongo-seed:
        build: ./mongo-seed
        networks:
            - biowaynet
        depends_on:
            - mongo
    ###

    ###Devops Pipeline
    jenkins:
        build: ./jenkins
        image: jenkins
        container_name: jenkins
        restart: always
        volumes:
            - jenkins-data:/var/jenkins_home
            - apigateway-data:/deploy-apigateway
            - cart-data:/deploy-cart
            - customers-data:/deploy-customers
            - eurekaserver-data:/deploy-eurekaserver
            - identity-data:/deploy-identity
            - payments-data:/deploy-payments
            - products-data:/deploy-products
            - ProductSearch-data:/deploy-ProductSearch
            - purchases-data:/deploy-purchases
            - suppliers-data:/deploy-suppliers
        ports:
            - 8090:8080
        networks:
            - biowaynet
    ###
    
networks:
    biowaynet:
        driver: bridge

volumes:
    gitea-data:
    apigateway-data:
    cart-data:
    customers-data:
    eurekaserver-data:
    identity-data:
    payments-data:
    products-data:
    ProductSearch-data:
    purchases-data:
    suppliers-data:
    jenkins-data: